config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :courses, only: [:index, :show]
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :sections, only: [] do
      resources :lessons, only: [:new, :create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :sections

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: "Unauthorized", status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end

end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
  end

private

def require_authorized_for_current_section
  if current_section.course.user != current_user
    return render text: 'Unauthorized', status: :unauthorized
  end
end

helper_method :current_section
def current_section
  @current_section ||= Section.find(params[:section_id])
end

def lesson_params
  params.require(:lesson).permit(:title, :subtitle)
end

end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course

  def new
    @section = Section.new
  end

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

private

def require_authorized_for_current_course
  if current_course.user != current_user
    render text: "Unauthorized", status: :unauthorized
  end
end

helper_method :current_course
def current_course
  @current_course ||= Course.find(params[:course_id])
end

def section_params
  params.require(:section).permit(:title)
end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
  end

  private

helper_method :current_lesson
def current_lesson
  @current_lesson ||= Lesson.find(params[:id])
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />

  <% @courses.each do |course| %>
  <h2 class="text-center">
    <%= link_to course.title, course_path(course) %>
    <%= image_tag course.image, class: 'img-fluid' %>
  </h2>
    <br />
    <div class="row">
      <div class="col-sm-8 col-12">
        <%= course.description %>
      </div>
      <div class="col-sm-4 col-12 text-center">
        <%= link_to 'More Details...', course_path(course), class: 'btn btn-primary btn-large' %>
      </div>
    </div>
    <br class="clr">
  <% end %>
</div>

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @course.title %></h1>
  <%= image_tag @course.image, class: 'img-fluid' %>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12 text-center">
      <span class="badge badge-default">
        <%= number_to_currency @course.cost %>
      </span>

      <% if current_user && current_user == @course.user %>
        <br />
        <br />
        <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
      <% end %>
    </div>

    <div class="col-sm-8 col-12">
      <% @course.sections.each do |section| %>
        <div class="section">
          <%= section.title %>
          <% section.lessons.each do |lesson| %>
            <div class="lesson">
              <%= link_to lesson_path(lesson) do %>
                <b><%= lesson.title %></b>
                -
                <%= lesson.subtitle %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
  <%= f.input :title %>
  <%= f.input :image %>
  <%= f.input :description %>
  <%= f.input :cost %>
  <br />
  <%= f.submit "Create", class: 'btn btn-primary' %>
  <br />
<% end %>
<br />
</div>

app/views/instructor/courses/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= current_course.title %>  <%= image_tag current_course.image, class: 'img-fluid' %></h1>
  <br \>
  <%= link_to 'Preview As Student...', course_path(current_course), class: 'btn btn-warning float-right' %>
  <br class="clr" />
  <div class="text-center">
    <%= link_to 'Add a new section...', new_instructor_course_section_path(current_course), class: 'btn btn-primary btn-lg' %>
  </div>
  <ul>
    <% current_course.sections.each do |section| %>
      <li>
        <%= section.title %>
        <%= link_to 'New Lesson', new_instructor_section_lesson_path(section), class: 'float-right btn btn-primary btn-sm' %>
        <ul>
          <% section.lessons.each do |lesson| %>
            <li>
              <b><%= lesson.title %></b>
              -
              <%= lesson.subtitle %>
            </li>
          <% end %>
        </ul>
        <br class="clr" />
      </li>
    <% end %>
  </ul>
</div>

app/views/instructor/lessons/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new lesson</h1>
  <%= simple_form_for @lesson, url: instructor_section_lessons_path(current_section) do |f| %>
  <%= f.input :title %>
  <%= f.input :subtitle %>
  <br \>
  <%= f.submit "Add the lesson" %>
  <br \>
  <br \>
<% end %>
</div>

app/views/instructor/sections/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new section</h1>
  <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
    <%= f.input :title %>
    <%= f.submit "Add a section", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flex-content-container">
    <nav class="navbar navbar-toggleable-md navbar-light bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Flixter', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to 'See All Courses', courses_path %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>

  <div id="footer">
    <div class="container">
      <b>Teachers</b>
      <br />
      <%= link_to 'Teach a Course', new_instructor_course_path %>
    </div>
  </div>
  </body>
</html>

app/views/lessons/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= current_lesson.title %></h1>
  <p>
    <%= current_lesson.subtitle %>
  </p>
</div>

app/views/static_pages/index.html.erb
<div class="hero">
  <br \>
      <div class="frosty col-10 offset-1 text-center">
        <br \>
        <h1>Learn Magic from the Pros</h1>
        <br \>
        <h2>I'm an illusionist, Michael.</h2>
        <br \>
        <%= link_to 'Learn More', courses_path, class: 'btn btn-success' %>
        <br \><br \>
    </div>
</div>

<br />
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <h3>Amazing Courses</h3>
    <br />
    <p>Choose from any number of courses to study with amazing teachers.</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Learn At Your Own Pace</h3>
    <br />
    <p>Enroll and access a courses archive of lessons.</p>
  </div>

  <div class="col-12 col-sm">
    <h3>Join our Community</h3>
    <br />
    <p>Learn with a community of like-minded individuals.</p>
  </div>
</div>